[project]
name = "xpath_identifier"
version = "0.0.9"
authors = [
  { name="Dev Tanna", email="dev.tanna@gmail.com" },
]
dependencies = [
    "beautifulsoup4==4.11.1",
    "lxml==4.9.1",
    "regex==2022.10.31",
]
description = "Identify Xpath expressions in a given document"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["xpath", "identifier", "parser"]

[project.urls]
"Homepage" = "https://github.com/devtanna/xpath-identifier"
"Bug Tracker" = "https://github.com/devtanna/xpath-identifier/issues"

[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
