[build-system]
requires = ["setuptools>=61.0","requests","pynput","pyautogui","bs4","selenium","imagehash","pyperclip","imagehash"]
build-backend = "setuptools.build_meta"
[project]
name = "webtilities"
version = "0.0.3"
authors = [
  { name="Lucas-AV", email="lucasvilela2014@gmail.com" },
]
description = "A python package to Scrapy data easily and facilitate some activities like division of list in sub lists to use in a multithreading code for example"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]