[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "frappy"
version = "0.0.1"
authors = [
  { name="Sandip V George", email="sandip.varkey@gmail.com" },
]
description = "Python package for non subjectively calculating the correlation dimension from time series data"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/sgeorge91/frappy"
"Bug Tracker" = "https://github.com/sgeorge91/frappy/issues"