paths: {}
components:
  schemas:
    AppSignalBase:
      properties:
        deprecated:
          example: false
          type: boolean
        excludedProperties:
          description: 'These properties have been dropped from the payload due to
            size.

            '
          items:
            type: string
          type: array
        type:
          nullable: false
          type: string
      required:
      - type
      - deprecated
      - excludedProperties
      type: object
    ButtonUiBlock:
      allOf:
      - $ref: '#/components/schemas/InteractiveUiBlock'
      - properties:
          text:
            example: Click me to submit
            type: string
          type:
            enum:
            - BUTTON
            type: string
        required:
        - type
        - text
      type: object
    Canvas:
      allOf:
      - $ref: '#/components/schemas/CanvasBase'
      - properties:
          id:
            example: cnvs_Q4mPJ34a
            type: string
      type: object
    CanvasBase:
      allOf:
      - $ref: '#/components/schemas/CanvasUiBlockList'
      - properties:
          enabled:
            description: 'Overall control for whether the canvas is interactable or
              not. If `false`, every block is disabled and will override the individual
              block''s `enabled` property. If `true` or absent, the interactivity
              status will defer to the block''s `enabled` property.

              '
            type: boolean
          featureId:
            description: Identifier of the feature defined in Benchling App Manifest
              this canvas corresponds to.
            type: string
          resourceId:
            description: Identifier of the resource object to attach canvas to.
            nullable: true
            type: string
        required:
        - featureId
      type: object
    CanvasInitializeWebhook:
      additionalProperties: false
      allOf:
      - $ref: '#/components/schemas/AppSignalBase'
      - properties:
          canvasId:
            nullable: false
            type: string
          featureId:
            nullable: false
            type: string
          type:
            enum:
            - v0-alpha.canvas.initialized
            nullable: false
            type: string
        required:
        - type
        - canvasId
        - featureId
        type: object
      description: Sent when a user initializes a canvas via trigger in the Benchling
        UI
    CanvasInteractionWebhook:
      additionalProperties: false
      allOf:
      - $ref: '#/components/schemas/AppSignalBase'
      - properties:
          buttonId:
            nullable: false
            type: string
          canvas:
            $ref: '#/components/schemas/Canvas'
          type:
            enum:
            - v0-alpha.canvas.userInteracted
            nullable: false
            type: string
        required:
        - type
        - buttonId
        - canvas
        type: object
      description: Sent when a user interacts with an app canvas via button press
    CanvasLeafNodeUiBlockList:
      properties:
        children:
          items:
            discriminator:
              mapping:
                BUTTON: '#/components/schemas/ButtonUiBlock'
                CHIP: '#/components/schemas/ChipUiBlock'
                DROPDOWN: '#/components/schemas/DropdownUiBlock'
                LABEL: '#/components/schemas/TextLabelUiBlock'
                MARKDOWN: '#/components/schemas/MarkdownUiBlock'
                SEARCH_INPUT: '#/components/schemas/SearchInputUiBlock'
                SELECTOR_INPUT: '#/components/schemas/SelectorInputUiBlock'
                TEXT_INPUT: '#/components/schemas/TextInputUiBlock'
              propertyName: type
            oneOf:
            - $ref: '#/components/schemas/ButtonUiBlock'
            - $ref: '#/components/schemas/ChipUiBlock'
            - $ref: '#/components/schemas/DropdownUiBlock'
            - $ref: '#/components/schemas/MarkdownUiBlock'
            - $ref: '#/components/schemas/SearchInputUiBlock'
            - $ref: '#/components/schemas/SelectorInputUiBlock'
            - $ref: '#/components/schemas/TextInputUiBlock'
            - $ref: '#/components/schemas/TextLabelUiBlock'
          type: array
      required:
      - children
      type: object
    CanvasUiBlockList:
      properties:
        blocks:
          items:
            discriminator:
              mapping:
                BUTTON: '#/components/schemas/ButtonUiBlock'
                CHIP: '#/components/schemas/ChipUiBlock'
                DROPDOWN: '#/components/schemas/DropdownUiBlock'
                LABEL: '#/components/schemas/TextLabelUiBlock'
                MARKDOWN: '#/components/schemas/MarkdownUiBlock'
                SEARCH_INPUT: '#/components/schemas/SearchInputUiBlock'
                SECTION: '#/components/schemas/SectionUiBlock'
                SELECTOR_INPUT: '#/components/schemas/SelectorInputUiBlock'
                TEXT_INPUT: '#/components/schemas/TextInputUiBlock'
              propertyName: type
            oneOf:
            - $ref: '#/components/schemas/ButtonUiBlock'
            - $ref: '#/components/schemas/ChipUiBlock'
            - $ref: '#/components/schemas/DropdownUiBlock'
            - $ref: '#/components/schemas/MarkdownUiBlock'
            - $ref: '#/components/schemas/SearchInputUiBlock'
            - $ref: '#/components/schemas/SectionUiBlock'
            - $ref: '#/components/schemas/SelectorInputUiBlock'
            - $ref: '#/components/schemas/TextInputUiBlock'
            - $ref: '#/components/schemas/TextLabelUiBlock'
          type: array
      required:
      - blocks
      type: object
    ChipUiBlock:
      allOf:
      - properties:
          type:
            enum:
            - CHIP
            type: string
          value:
            type: string
        required:
        - type
        - value
      type: object
    DropdownUiBlock:
      allOf:
      - $ref: '#/components/schemas/UserInputUiBlock'
      - properties:
          dropdownId:
            type: string
          type:
            enum:
            - DROPDOWN
            type: string
        required:
        - type
        - dropdownId
      type: object
    InteractiveUiBlock:
      properties:
        enabled:
          nullable: true
          type: boolean
        id:
          example: user_defined_id
          type: string
      required:
      - id
      type: object
    LifecycleActivateWebhook:
      additionalProperties: false
      allOf:
      - $ref: '#/components/schemas/AppSignalBase'
      - properties:
          clientId:
            nullable: false
            type: string
          clientSecret:
            nullable: false
            type: string
          type:
            enum:
            - v0-alpha.app.activateRequested
            nullable: false
            type: string
        required:
        - clientId
        - clientSecret
        type: object
      description: Sent when a user initiates app activation on a tenant
    LifecycleDeactivateWebhook:
      additionalProperties: false
      allOf:
      - $ref: '#/components/schemas/AppSignalBase'
      - properties:
          type:
            enum:
            - v0-alpha.app.deactivated
            nullable: false
            type: string
        type: object
      description: Sent when a user initiates app deactivation on a tenant
    MarkdownUiBlock:
      additionalProperties: false
      properties:
        type:
          enum:
          - MARKDOWN
          type: string
        value:
          example: '# This is a markdown block

            1. with **bold text**.'
          type: string
      required:
      - type
      - value
      type: object
    SearchInputUiBlock:
      allOf:
      - $ref: '#/components/schemas/UserInputUiBlock'
      - properties:
          itemType:
            enum:
            - dna_sequence
            - dna_oligo
            - aa_sequence
            - custom_entity
            - mixture
            - box
            - container
            - location
            - plate
            type: string
          schemaId:
            nullable: true
            type: string
          type:
            enum:
            - SEARCH_INPUT
            type: string
        required:
        - type
        - itemType
        - schemaId
      type: object
    SectionUiBlock:
      allOf:
      - $ref: '#/components/schemas/CanvasLeafNodeUiBlockList'
      - properties:
          type:
            enum:
            - SECTION
            type: string
      type: object
    SelectorInputUiBlock:
      allOf:
      - $ref: '#/components/schemas/UserInputUiBlock'
      - properties:
          options:
            items:
              type: string
            type: array
          type:
            enum:
            - SELECTOR_INPUT
            type: string
        required:
        - type
        - options
      type: object
    TextInputUiBlock:
      allOf:
      - $ref: '#/components/schemas/UserInputUiBlock'
      - properties:
          placeholder:
            nullable: true
            type: string
          type:
            enum:
            - TEXT_INPUT
            type: string
        required:
        - type
      type: object
    TextLabelUiBlock:
      additionalProperties: false
      properties:
        text:
          example: This is a label element.
          type: string
        type:
          enum:
          - LABEL
          type: string
      required:
      - type
      - text
      type: object
    UserInputUiBlock:
      allOf:
      - $ref: '#/components/schemas/InteractiveUiBlock'
      - properties:
          value:
            nullable: true
            type: string
        required:
        - value
      type: object
    WebhookMessage:
      discriminator:
        mapping:
          v0-alpha.app.activateRequested: '#/components/schemas/LifecycleActivateWebhook'
          v0-alpha.app.inactive: '#/components/schemas/LifecycleDeactivateWebhook'
          v0-alpha.canvas.initialized: '#/components/schemas/CanvasInitializeWebhook'
          v0-alpha.canvas.userInteracted: '#/components/schemas/CanvasInteractionWebhook'
        propertyName: type
      oneOf:
      - $ref: '#/components/schemas/LifecycleActivateWebhook'
      - $ref: '#/components/schemas/LifecycleDeactivateWebhook'
      - $ref: '#/components/schemas/CanvasInteractionWebhook'
      - $ref: '#/components/schemas/CanvasInitializeWebhook'
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Benchling Apps Webhooks
  version: 2.0.0
openapi: 3.0.1
servers:
- url: webhooks
