[project]
name = "AMCowmvg"
version = "1.0.2"
description = "Produce Antimony Files and Graphs using a browser GUI"
authors = [{ name = "Olivia Walsh", email = "owalsh@uw.edu" }, { name = "Matthew Van Ginneken", email = "mattcvang@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.6"

dependencies = [
    "tellurium",
    "flask",
    "wtforms",
    "matplotlib",
]

[project.urls]
Homepage = "https://github.com/MatthewVanG/AMC-OWMVG"

[project.scripts]
AMCowmvg = "AMCowmvg.__main__:runApp"

[tool.setuptools]
# ...
# By default, include-package-data is true in pyproject.toml, so you do
# NOT have to specify this line.
include-package-data = true

[tool.setuptools.packages.find]
where = ["AMCowmvg"]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"