[project]
name = "stampa"
version = "0.1.0"
authors = [
  { name="Evzen Ptacek", email="p1463k@gmail.com" },
]
description = "Generates date time as string without spaces"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/3p1463k/stampa"
"Bug Tracker" = "https://github.com/3p1463k/stampa/issues"
