[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "backto1"
version = "0.0.1"
description = "A small command line tool for converting openLCA 2 JSON packages back to version 1."
readme = "README.md"
requires-python = ">=3.11"
keywords = [
    "openLCA",
    "life cycle assessment",
    "LCA"
]
dependencies = [
    "olca-schema>=0.0.9"
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Topic :: Utilities",
]

[project.scripts]
backto1 = "backto1:main"

[project.urls]
"Homepage" = "https://github.com/msrocka/backto1"
"Bug Tracker" = "https://github.com/msrocka/backto1/issues"

[tool.setuptools.packages.find]
include = ["backto1"]
exclude = ["tests"]
