[tool.poetry]
name = "datagen-tech"
version = "1.4.13"
description = "Datagen SDK"
readme = "README.md"
authors = ["Datagen Technologies Ltd."]
packages = [{ include = "datagen", from ="src"}]
repository = "https://gitlab.com/datagen1/core/sdk"

[tool.poetry.dependencies]
python = ">=3.6.7 ,<4.0.0"
dependency-injector = ">4.6"
marshmallow-dataclass = ">=6"
marshmallow-enum = ">=1.5"
numpy  = [
    { "version" = "^1.15", python = ">=3.6.7 ,<3.7" },
    { "version" = "^1.19", python = ">=3.7,<3.8" },
    { "version" = "^1.20", python = ">=3.8,<3.9" },
    { "version" = ">=1.20", python = ">=3.9" }
]
pillow = ">=7.0"
opencv-python = ">=4.4"

jupyter = ">=1.0"
pydantic = ">=1.9"
rich = ">=12.5"
beautifulsoup4 = ">=4.11"
dynaconf = ">=3.0"
importlib-metadata = "<5.0.0"
pandas = ">=1.3"

[tool.poetry.dev-dependencies]
pytest = ">=6"
Sphinx= ">=5.1.1"
sphinx-rtd-theme = ">=1.0.0"
sphinxcontrib-apidoc = ">=0.3.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "/tests/unit/"
]
pythonpath = [
    ".", "src",
]

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/

)
'''

[tool.isort]
line_length = 120
profile = "black"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"