[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "funAD"
version = "0.1.2"
authors = [
  { name="Hanlin Zhu", email="hzhu@g.harvard.edu" },
  { name="Xu Tang", email="xutang@g.harvard.edu" },
  { name="Tiantong Li", email="tiantongli@g.harvard.edu" },
  { name="Zhecheng Yao", email="zhechengyao@g.harvard.edu" },
]
description = "an automatic differentiation package created by AC207 students"
readme = "README.md"
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Topic :: Software Development :: Testing"
]
dependencies = [
    "numpy",
    "pytest",
]

[tool.setuptools]
# ...
package-dir = {"" = "src"}
    # directory containing all the packages (e.g.  src/mypkg1, src/mypkg2)


[project.urls]
"Homepage" = "https://code.harvard.edu/CS107/team21"
