[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project]
name = "lwjs"
version = "0.9.0"
authors = [ { name="Andrei Hes", email="andrei.hes@ya.ru" } ]
description = "LightWeight JSON Shell"
readme = "README.pypi.md"
license = "WTFPL"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/andreihes/lwjs"
"Bug Tracker" = "https://github.com/andreihes/lwjs/issues"

[tool.hatch.build.targets.wheel]
only-include = [ "lwjs" ]
