[tool.poetry]
name = "mappi"
version = "0.6.0"
description = "Spin up webserver from a yaml config file"
authors = ["Misha Behersky <bmwant@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fastapi = "^0.87.0"
uvicorn = "^0.20.0"
PyYAML = "^6.0"
rich = "^12.6.0"

[tool.poetry.scripts]
mappi = 'mappi.cli:cli'

[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
black = "^22.10.0"
flake8 = "^6.0.0"
pytest = "^7.2.0"
coverage = "^6.5.0"
requests = "^2.28.1"
python-semantic-release = "^7.32.2"

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
branch = "release"
upload_to_repository = false
upload_to_release = false  # do not upload distribution to GH releases
build_command = false
major_on_zero = false
tag_commit = true
commit_subject = "Release {version}"
changelog_file = "CHANGELOG.md"
changelog_scope = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
