[tool.poetry]
name = "mkdocs-caseinsensitive-plugin"
version = "0.1.0"
description = ""
authors = ["TheMythologist <leekaixuan2001@gmail.com>"]
license = "AGPL V3"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.4.2"

[tool.poetry.plugins]

[tool.poetry.plugins."mkdocs.plugins"]
caseinsensitivefiles = "src:CaseInsensitiveFiles"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
flake8 = "^6.0.0"
pyproject-flake8 = "^6.0.0"

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
