[tool.poetry]
name = "echaim"
version = "1.0.8"
description = "A Python wrapper to the E-CHAIM C source code."
authors = ["lap1dem <vadym.bidula@gmail.com>"]
readme = "README.md"
build = "build.py"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22"
tqdm = "^4.64.1"
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.1.1"
sphinx-autodoc-typehints = "^1.19.5"
sphinxcontrib-bibtex = "^2.5.0"


[tool.poetry.group.dev.dependencies]
setuptools-cpp = "^0.1.0"
matplotlib = "^3.6.2"
pyqt5 = "^5.15.7"

[build-system]
requires = ["cmake", "poetry-core",  "wheel", "setuptools-cpp"]
build-backend = "poetry.core.masonry.api"
