[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "aeda"
version = "2022.12.20"
authors = [
  { name="Sven Haadem", email="sven@aeda.no" },
]
description = "Aeda car API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
]
[project.urls]
"Homepage" = "https://github.com/pypa/aeda"
"Bug Tracker" = "https://github.com/pypa/aeda/issues"
[tool.bumpver]
current_version = "2022.12.20"
version_pattern = "YYYY.MM.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true
[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']


