[tool.poetry]
name = "midas_dev"
version = "0.45.0"
description = ""
authors = ["Anton V <anton.vasilyev@midas.investments>"]

[tool.poetry.scripts]
midautoflake = "midas_dev.main:Autoflake.run_cli"
midblack = "midas_dev.main:Black.run_cli"
middeploy = "midas_dev.deploy:DeployManager.run_cli"
midflake8 = "midas_dev.main:Flake8.run_cli"
midfmt = "midas_dev.main:Format.run_cli"
midisort = "midas_dev.main:ISort.run_cli"
mid = "midas_dev.main:Fulltest.run_cli"
midmypy = "midas_dev.main:Mypy.run_cli"
midpytest = "midas_dev.main:Pytest.run_cli"
midtest = "midas_dev.main:Fulltest.run_cli"

[tool.poetry.dependencies]
python = "^3.10"
# Libs
click = "^8.1.3"
toml = "^0.10.2"
# Tooling
poetry = "^1.2.2"
poetryup = "^0.12.5"
pre-commit = "^2.20.0"
# Debug conveniences
coloredlogs = "^15.0.1"
ipdb = "^0.13.9"
# Formatting
autoflake = "^1.7.8"
black = "^22.10.0"
isort = "^5.10.1"
# `flake8`
flake8 = "^5.0.4"
flake8-broken-line = "^0.6.0"
flake8-debugger = "^4.1.2"
flake8-mock-x2 = "^0.4.1"
flake8-print = "^5.0.0"
flake8-pytest-style = "^1.6.0"
flake8-use-fstring = "^1.4"
# `mypy`
mypy = "^0.991"
# `pytest`
pytest = "^7.2.0"
pytest-asyncio = "^0.20.2"
pytest-blockage = "^0.2.4"
pytest-cov = "^4.0.0"
pytest-deadfixtures = "^2.2.1"
pytest-env = "^0.8.1"
pytest-timeout = "^2.1.0"
# `django`
django-coverage-plugin = {version = "^2.0.4", optional = true}
django-debug-toolbar = {version = "^3.7.0", optional = true}
django-extra-checks = {version = "^0.13.3", optional = true}
django-migration-linter = {version = "^4.1.0", optional = true}
django-querycount = {version = "^0.7.0", optional = true}
django-split-settings = {version = "^1.2.0", optional = true}
django-stubs = {version = "^1.13.0", optional = true}
django-stubs-ext = {version = "^0.7.0", optional = true}
django-test-migrations = {version = "^1.2.0", optional = true}
flake8-django = {version = "^1.1.5", optional = true}
pytest-django = {version = "^4.5.2", optional = true}

[tool.poetry.extras]
django = [
  "django-coverage-plugin",
  "django-debug-toolbar",
  "django-extra-checks",
  "django-migration-linter",
  "django-querycount",
  "django-split-settings",
  "django-stubs",
  "django-stubs-ext",
  "django-test-migrations",
  "flake8-django",
  "pytest-django",
]

[tool.poetry.group.dev.dependencies]
types-toml = "^0.10.8.1"
types-requests = "^2.28.11.5"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
